<?php
return array (
  'stickiesSheetActions' => 'wa-apps\\stickies/lib/actions/sheet/stickiesSheet.actions.php',
  'stickiesBackendAction' => 'wa-apps\\stickies/lib/actions/stickiesBackend.action.php',
  'stickiesStickyActions' => 'wa-apps\\stickies/lib/actions/sticky/stickiesSticky.actions.php',
  'stickiesAPIMethod' => 'wa-apps\\stickies/lib/classes/stickiesAPIMethod.class.php',
  'stickiesModel' => 'wa-apps\\stickies/lib/classes/stickiesModel.class.php',
  'stickiesConfig' => 'wa-apps\\stickies/lib/config/stickiesConfig.class.php',
  'stickiesRightConfig' => 'wa-apps\\stickies/lib/config/stickiesRightConfig.class.php',
  'stickiesJsonActionsController' => 'wa-apps\\stickies/lib/controller/stickiesJsonActions.controller.php',
  'stickiesSheetModel' => 'wa-apps\\stickies/lib/models/stickiesSheet.model.php',
  'stickiesStickyModel' => 'wa-apps\\stickies/lib/models/stickiesSticky.model.php',
  'stickiesSheetAddMethod' => 'wa-apps\\stickies/api/v1/stickies.sheet.add.method.php',
  'stickiesSheetDeleteMethod' => 'wa-apps\\stickies/api/v1/stickies.sheet.delete.method.php',
  'stickiesSheetGetInfoMethod' => 'wa-apps\\stickies/api/v1/stickies.sheet.getInfo.method.php',
  'stickiesSheetGetListMethod' => 'wa-apps\\stickies/api/v1/stickies.sheet.getList.method.php',
  'stickiesSheetUpdateMethod' => 'wa-apps\\stickies/api/v1/stickies.sheet.update.method.php',
  'stickiesStickyAddMethod' => 'wa-apps\\stickies/api/v1/stickies.sticky.add.method.php',
  'stickiesStickyDeleteMethod' => 'wa-apps\\stickies/api/v1/stickies.sticky.delete.method.php',
  'stickiesStickyGetInfoMethod' => 'wa-apps\\stickies/api/v1/stickies.sticky.getInfo.method.php',
  'stickiesStickyGetListMethod' => 'wa-apps\\stickies/api/v1/stickies.sticky.getList.method.php',
  'stickiesStickyUpdateMethod' => 'wa-apps\\stickies/api/v1/stickies.sticky.update.method.php',
);